//SmallCompany_ver3_3.cs, 780 lines 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace https.markpelf.com.SmallCompany.xsd {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Linq;
    using Xml.Schema.Linq;
    
    
    /// <summary>
    /// <para>
    /// Regular expression: (CompanyName, Employee+, InfoData+)
    /// </para>
    /// </summary>
    public partial class SmallCompany : XTypedElement, IXMetaData {
        
        public void Save(string xmlFile) {
            XTypedServices.Save(xmlFile, Untyped);
        }
        
        public void Save(System.IO.TextWriter tw) {
            XTypedServices.Save(tw, Untyped);
        }
        
        public void Save(System.Xml.XmlWriter xmlWriter) {
            XTypedServices.Save(xmlWriter, Untyped);
        }
        
        public static SmallCompany Load(string xmlFile) {
            return XTypedServices.Load<SmallCompany>(xmlFile);
        }
        
        public static SmallCompany Load(System.IO.TextReader xmlFile) {
            return XTypedServices.Load<SmallCompany>(xmlFile);
        }
        
        public static SmallCompany Parse(string xml) {
            return XTypedServices.Parse<SmallCompany>(xml);
        }
        
		public static explicit operator SmallCompany(XElement xe) { return XTypedServices.ToXTypedElement<SmallCompany>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
        
        public override XTypedElement Clone() {
            return XTypedServices.CloneXTypedElement<SmallCompany>(this);
        }
        
        /// <summary>
        /// <para>
        /// Regular expression: (CompanyName, Employee+, InfoData+)
        /// </para>
        /// </summary>
        public SmallCompany() {
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName CompanyNameXName = System.Xml.Linq.XName.Get("CompanyName", "https://markpelf.com/SmallCompany.xsd");
        
        /// <summary>
        /// <para>
        /// Occurrence: required
        /// </para>
        /// <para>
        /// Regular expression: (CompanyName, Employee+, InfoData+)
        /// </para>
        /// </summary>
        public virtual string CompanyName {
            get {
                XElement x = this.GetElement(CompanyNameXName);
                return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
            }
            set {
                this.SetElement(CompanyNameXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName EmployeeXName = System.Xml.Linq.XName.Get("Employee", "https://markpelf.com/SmallCompany.xsd");
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.EmployeeLocalType> EmployeeField;
        
        /// <summary>
        /// <para>
        /// Occurrence: required, repeating
        /// </para>
        /// <para>
        /// Regular expression: (CompanyName, Employee+, InfoData+)
        /// </para>
        /// </summary>
        public virtual IList<https.markpelf.com.SmallCompany.xsd.SmallCompany.EmployeeLocalType> Employee {
            get {
                if ((this.EmployeeField == null)) {
                    this.EmployeeField = new XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.EmployeeLocalType>(this, LinqToXsdTypeManager.Instance, EmployeeXName);
                }
                return this.EmployeeField;
            }
            set {
                if ((value == null)) {
                    this.EmployeeField = null;
                }
                else {
                    if ((this.EmployeeField == null)) {
                        this.EmployeeField = XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.EmployeeLocalType>.Initialize(this, LinqToXsdTypeManager.Instance, value, EmployeeXName);
                    }
                    else {
                        XTypedServices.SetList<https.markpelf.com.SmallCompany.xsd.SmallCompany.EmployeeLocalType>(this.EmployeeField, value);
                    }
                }
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName InfoDataXName = System.Xml.Linq.XName.Get("InfoData", "https://markpelf.com/SmallCompany.xsd");
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.InfoDataLocalType> InfoDataField;
        
        /// <summary>
        /// <para>
        /// Occurrence: required, repeating
        /// </para>
        /// <para>
        /// Regular expression: (CompanyName, Employee+, InfoData+)
        /// </para>
        /// </summary>
        public virtual IList<https.markpelf.com.SmallCompany.xsd.SmallCompany.InfoDataLocalType> InfoData {
            get {
                if ((this.InfoDataField == null)) {
                    this.InfoDataField = new XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.InfoDataLocalType>(this, LinqToXsdTypeManager.Instance, InfoDataXName);
                }
                return this.InfoDataField;
            }
            set {
                if ((value == null)) {
                    this.InfoDataField = null;
                }
                else {
                    if ((this.InfoDataField == null)) {
                        this.InfoDataField = XTypedList<https.markpelf.com.SmallCompany.xsd.SmallCompany.InfoDataLocalType>.Initialize(this, LinqToXsdTypeManager.Instance, value, InfoDataXName);
                    }
                    else {
                        XTypedServices.SetList<https.markpelf.com.SmallCompany.xsd.SmallCompany.InfoDataLocalType>(this.InfoDataField, value);
                    }
                }
            }
        }
        
        private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("SmallCompany", "https://markpelf.com/SmallCompany.xsd");
        
        static SmallCompany() {
            BuildElementDictionary();
            contentModel = new SequenceContentModelEntity(new NamedContentModelEntity(CompanyNameXName), new NamedContentModelEntity(EmployeeXName), new NamedContentModelEntity(InfoDataXName));
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static Dictionary<System.Xml.Linq.XName, System.Type> localElementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
        
        private static void BuildElementDictionary() {
            localElementDictionary.Add(CompanyNameXName, typeof(string));
            localElementDictionary.Add(EmployeeXName, typeof(EmployeeLocalType));
            localElementDictionary.Add(InfoDataXName, typeof(InfoDataLocalType));
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
            get {
                return localElementDictionary;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static ContentModelEntity contentModel;
        
        ContentModelEntity IXMetaData.GetContentModel() {
            return contentModel;
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        System.Xml.Linq.XName IXMetaData.SchemaName {
            get {
                return xName;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        SchemaOrigin IXMetaData.TypeOrigin {
            get {
                return SchemaOrigin.Element;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILinqToXsdTypeManager IXMetaData.TypeManager {
            get {
                return LinqToXsdTypeManager.Instance;
            }
        }
        
        /// <summary>
        /// <para>
        /// Regular expression: (Name_String_NO, City_String_O?)
        /// </para>
        /// </summary>
        public partial class EmployeeLocalType : XTypedElement, IXMetaData {
            
		public static explicit operator EmployeeLocalType(XElement xe) { return XTypedServices.ToXTypedElement<EmployeeLocalType>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
            
            public override XTypedElement Clone() {
                return XTypedServices.CloneXTypedElement<EmployeeLocalType>(this);
            }
            
            /// <summary>
            /// <para>
            /// Regular expression: (Name_String_NO, City_String_O?)
            /// </para>
            /// </summary>
            public EmployeeLocalType() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected internal static readonly System.Xml.Linq.XName Name_String_NOXName = System.Xml.Linq.XName.Get("Name_String_NO", "https://markpelf.com/SmallCompany.xsd");
            
            /// <summary>
            /// <para>
            /// Occurrence: required
            /// </para>
            /// <para>
            /// Regular expression: (Name_String_NO, City_String_O?)
            /// </para>
            /// </summary>
            public virtual string Name_String_NO {
                get {
                    XElement x = this.GetElement(Name_String_NOXName);
                    return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
                }
                set {
                    this.SetElement(Name_String_NOXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected internal static readonly System.Xml.Linq.XName City_String_OXName = System.Xml.Linq.XName.Get("City_String_O", "https://markpelf.com/SmallCompany.xsd");
            
            /// <summary>
            /// <para>
            /// Occurrence: optional
            /// </para>
            /// <para>
            /// Regular expression: (Name_String_NO, City_String_O?)
            /// </para>
            /// </summary>
            public virtual string City_String_O {
                get {
                    XElement x = this.GetElement(City_String_OXName);
                    if ((x == null)) {
                        return null;
                    }
                    return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
                }
                set {
                    this.SetElement(City_String_OXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
                }
            }
            
            private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("Employee", "https://markpelf.com/SmallCompany.xsd");
            
            static EmployeeLocalType() {
                BuildElementDictionary();
                contentModel = new SequenceContentModelEntity(new NamedContentModelEntity(Name_String_NOXName), new NamedContentModelEntity(City_String_OXName));
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            private static Dictionary<System.Xml.Linq.XName, System.Type> localElementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
            
            private static void BuildElementDictionary() {
                localElementDictionary.Add(Name_String_NOXName, typeof(string));
                localElementDictionary.Add(City_String_OXName, typeof(string));
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
                get {
                    return localElementDictionary;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            private static ContentModelEntity contentModel;
            
            ContentModelEntity IXMetaData.GetContentModel() {
                return contentModel;
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            System.Xml.Linq.XName IXMetaData.SchemaName {
                get {
                    return xName;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            SchemaOrigin IXMetaData.TypeOrigin {
                get {
                    return SchemaOrigin.Fragment;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            ILinqToXsdTypeManager IXMetaData.TypeManager {
                get {
                    return LinqToXsdTypeManager.Instance;
                }
            }
        }
        
        /// <summary>
        /// <para>
        /// Regular expression: (Id_Int_NO, Quantity_Int_O?)
        /// </para>
        /// </summary>
        public partial class InfoDataLocalType : XTypedElement, IXMetaData {
            
		public static explicit operator InfoDataLocalType(XElement xe) { return XTypedServices.ToXTypedElement<InfoDataLocalType>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
            
            public override XTypedElement Clone() {
                return XTypedServices.CloneXTypedElement<InfoDataLocalType>(this);
            }
            
            /// <summary>
            /// <para>
            /// Regular expression: (Id_Int_NO, Quantity_Int_O?)
            /// </para>
            /// </summary>
            public InfoDataLocalType() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected internal static readonly System.Xml.Linq.XName Id_Int_NOXName = System.Xml.Linq.XName.Get("Id_Int_NO", "https://markpelf.com/SmallCompany.xsd");
            
            /// <summary>
            /// <para>
            /// Occurrence: required
            /// </para>
            /// <para>
            /// Regular expression: (Id_Int_NO, Quantity_Int_O?)
            /// </para>
            /// </summary>
            public virtual int Id_Int_NO {
                get {
                    XElement x = this.GetElement(Id_Int_NOXName);
                    return XTypedServices.ParseValue<int>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Int).Datatype);
                }
                set {
                    this.SetElement(Id_Int_NOXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Int).Datatype);
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected internal static readonly System.Xml.Linq.XName Quantity_Int_OXName = System.Xml.Linq.XName.Get("Quantity_Int_O", "https://markpelf.com/SmallCompany.xsd");
            
            /// <summary>
            /// <para>
            /// Occurrence: optional
            /// </para>
            /// <para>
            /// Regular expression: (Id_Int_NO, Quantity_Int_O?)
            /// </para>
            /// </summary>
            public virtual System.Int32? Quantity_Int_O {
                get {
                    XElement x = this.GetElement(Quantity_Int_OXName);
                    if ((x == null)) {
                        return null;
                    }
                    return XTypedServices.ParseValue<int>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Int).Datatype);
                }
                set {
                    this.SetElement(Quantity_Int_OXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Int).Datatype);
                }
            }
            
            private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("InfoData", "https://markpelf.com/SmallCompany.xsd");
            
            static InfoDataLocalType() {
                BuildElementDictionary();
                contentModel = new SequenceContentModelEntity(new NamedContentModelEntity(Id_Int_NOXName), new NamedContentModelEntity(Quantity_Int_OXName));
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            private static Dictionary<System.Xml.Linq.XName, System.Type> localElementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
            
            private static void BuildElementDictionary() {
                localElementDictionary.Add(Id_Int_NOXName, typeof(int));
                localElementDictionary.Add(Quantity_Int_OXName, typeof(int));
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
                get {
                    return localElementDictionary;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            private static ContentModelEntity contentModel;
            
            ContentModelEntity IXMetaData.GetContentModel() {
                return contentModel;
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            System.Xml.Linq.XName IXMetaData.SchemaName {
                get {
                    return xName;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            SchemaOrigin IXMetaData.TypeOrigin {
                get {
                    return SchemaOrigin.Fragment;
                }
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            ILinqToXsdTypeManager IXMetaData.TypeManager {
                get {
                    return LinqToXsdTypeManager.Instance;
                }
            }
        }
    }
    
    public class LinqToXsdTypeManager : ILinqToXsdTypeManager {
        
        private LinqToXsdTypeManager() {
        }
        
        private static Dictionary<System.Xml.Linq.XName, System.Type> elementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
        
        private static void BuildElementDictionary() {
            elementDictionary.Add(System.Xml.Linq.XName.Get("SmallCompany", "https://markpelf.com/SmallCompany.xsd"), typeof(global::https.markpelf.com.SmallCompany.xsd.SmallCompany));
        }
        
        private static XmlSchemaSet schemaSet;
        
        XmlSchemaSet ILinqToXsdTypeManager.Schemas {
            get {
                if ((schemaSet == null)) {
                    XmlSchemaSet tempSet = new XmlSchemaSet();
                    System.Threading.Interlocked.CompareExchange(ref schemaSet, tempSet, null);
                }
                return schemaSet;
            }
            set {
                schemaSet = value;
            }
        }
        
        protected internal static void AddSchemas(XmlSchemaSet schemas) {
            schemas.Add(schemaSet);
        }
        
        Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalTypeDictionary {
            get {
                return XTypedServices.EmptyDictionary;
            }
        }
        
        Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalElementDictionary {
            get {
                return elementDictionary;
            }
        }
        
        Dictionary<System.Type, System.Type> ILinqToXsdTypeManager.RootContentTypeMapping {
            get {
                return XTypedServices.EmptyTypeMappingDictionary;
            }
        }
        
        static LinqToXsdTypeManager() {
            BuildElementDictionary();
        }
        
        public static System.Type GetRootType() {
            return elementDictionary[System.Xml.Linq.XName.Get("SmallCompany", "https://markpelf.com/SmallCompany.xsd")];
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static LinqToXsdTypeManager typeManagerSingleton = new LinqToXsdTypeManager();
        
        public static LinqToXsdTypeManager Instance {
            get {
                return typeManagerSingleton;
            }
        }
    }
    
    public partial class XRootNamespace {
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XDocument doc;
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedElement rootObject;
        
        private XRootNamespace() {
        }
        
        public static XRootNamespace Load(string xmlFile) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlFile);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(string xmlFile, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlFile, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(TextReader textReader) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(textReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(TextReader textReader, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(textReader, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(XmlReader xmlReader) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Parse(string text) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Parse(text);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Parse(string text, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Parse(text, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public virtual void Save(string fileName) {
            doc.Save(fileName);
        }
        
        public virtual void Save(TextWriter textWriter) {
            doc.Save(textWriter);
        }
        
        public virtual void Save(XmlWriter writer) {
            doc.Save(writer);
        }
        
        public virtual void Save(TextWriter textWriter, SaveOptions options) {
            doc.Save(textWriter, options);
        }
        
        public virtual void Save(string fileName, SaveOptions options) {
            doc.Save(fileName, options);
        }
        
        public virtual XDocument XDocument {
            get {
                return doc;
            }
        }
        
        public virtual XTypedElement Root {
            get {
                return rootObject;
            }
        }
        
        public XRootNamespace(SmallCompany root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public SmallCompany SmallCompany {  get {return rootObject as SmallCompany; } }
    }
    
    public partial class XRoot {
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XDocument doc;
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedElement rootObject;
        
        private XRoot() {
        }
        
        public static XRoot Load(string xmlFile) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlFile);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(string xmlFile, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlFile, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(TextReader textReader) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(textReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(TextReader textReader, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(textReader, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(XmlReader xmlReader) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Parse(string text) {
            XRoot root = new XRoot();
            root.doc = XDocument.Parse(text);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Parse(string text, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Parse(text, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public virtual void Save(string fileName) {
            doc.Save(fileName);
        }
        
        public virtual void Save(TextWriter textWriter) {
            doc.Save(textWriter);
        }
        
        public virtual void Save(XmlWriter writer) {
            doc.Save(writer);
        }
        
        public virtual void Save(TextWriter textWriter, SaveOptions options) {
            doc.Save(textWriter, options);
        }
        
        public virtual void Save(string fileName, SaveOptions options) {
            doc.Save(fileName, options);
        }
        
        public virtual XDocument XDocument {
            get {
                return doc;
            }
        }
        
        public virtual XTypedElement Root {
            get {
                return rootObject;
            }
        }
        
        public XRoot(global::https.markpelf.com.SmallCompany.xsd.SmallCompany root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public global::https.markpelf.com.SmallCompany.xsd.SmallCompany SmallCompany {  get {return rootObject as global::https.markpelf.com.SmallCompany.xsd.SmallCompany; } }
    }
}
