// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ClassLibraryA.EF_Northwind;

namespace ClassLibraryA.EF_Northwind
{
    public partial class NorthwindContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
