//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace Example1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://markpelf.com/BigCompany.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://markpelf.com/BigCompany.xsd", IsNullable=false)]
    public partial class BigCompany {
        
        private string companyNameField;
        
        private BigCompanyEmployee[] employeeField;
        
        private BigCompanyInfoData[] infoDataField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employee")]
        public BigCompanyEmployee[] Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfoData")]
        public BigCompanyInfoData[] InfoData {
            get {
                return this.infoDataField;
            }
            set {
                this.infoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://markpelf.com/BigCompany.xsd")]
    public partial class BigCompanyEmployee {
        
        private string name_String_NOField;
        
        private string city_String_OField;
        
        /// <remarks/>
        public string Name_String_NO {
            get {
                return this.name_String_NOField;
            }
            set {
                this.name_String_NOField = value;
            }
        }
        
        /// <remarks/>
        public string City_String_O {
            get {
                return this.city_String_OField;
            }
            set {
                this.city_String_OField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://markpelf.com/BigCompany.xsd")]
    public partial class BigCompanyInfoData {
        
        private int data1_Int_NO_RField;
        
        private System.Nullable<int> data2_Int_NO_NRField;
        
        private int data3_Int_O_RField;
        
        private bool data3_Int_O_RFieldSpecified;
        
        private System.Nullable<int> data4_Int_O_NRField;
        
        private bool data4_Int_O_NRFieldSpecified;
        
        /// <remarks/>
        public int Data1_Int_NO_R {
            get {
                return this.data1_Int_NO_RField;
            }
            set {
                this.data1_Int_NO_RField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Data2_Int_NO_NR {
            get {
                return this.data2_Int_NO_NRField;
            }
            set {
                this.data2_Int_NO_NRField = value;
            }
        }
        
        /// <remarks/>
        public int Data3_Int_O_R {
            get {
                return this.data3_Int_O_RField;
            }
            set {
                this.data3_Int_O_RField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Data3_Int_O_RSpecified {
            get {
                return this.data3_Int_O_RFieldSpecified;
            }
            set {
                this.data3_Int_O_RFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Data4_Int_O_NR {
            get {
                return this.data4_Int_O_NRField;
            }
            set {
                this.data4_Int_O_NRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Data4_Int_O_NRSpecified {
            get {
                return this.data4_Int_O_NRFieldSpecified;
            }
            set {
                this.data4_Int_O_NRFieldSpecified = value;
            }
        }
    }
}
